### ISSUE TITLE
Can't load the rust_x64_elf.sig

### ISSUE THREAD

**Issue by 0xsmirk** [cha5126568/rust-reversing-helper#2]
the rust_x64_elf.sig in the D:\IDA_Pro_v7.5_Portable\sig，then i shift+f5 , can't to find the rust_x64_elf.sig! why?
![image](https://user-images.githubusercontent.com/54340060/119939062-dc437800-bfbf-11eb-9e65-84b727aba16c.png)

![image](https://user-images.githubusercontent.com/54340060/119939144-f5e4bf80-bfbf-11eb-84e8-615786aceded.png)

![image](https://user-images.githubusercontent.com/54340060/119939199-0d23ad00-bfc0-11eb-9c9f-888d4f29dd19.png)

i deal with the demo by strip on linux.

**Comment by cha512** [comment]
It should be placed in the sig\pc\ folder, press shift+f5 and press insert to load.

And that signature was made almost three years ago, so if you want to use flirt properly, make flirt sigunature yourself and use it.

**Comment by 0xsmirk** [comment]
thanks



---Original---
From: ***@***.***&gt;
Date: Fri, May 28, 2021 14:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cha5126568/rust-reversing-helper] Can't load the rust_x64_elf.sig (#2)




 
It should be placed in the sig\pc\ folder, press shift+f5 and press insert to load.
 
And that signature was made almost three years ago, so if you want to use flirt properly, make flirt sigunature yourself and use it.
